# Navigation Links

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 15
  - name: Papers
    url: /#papers
    weight: 20
  - name: Presentations
    url: /#presentations
    weight: 25
  - name: Teaching
    url: /#teaching
    weight: 30
  - name: Projects
    url: /#projects
    weight: 35
  - name: Contact
    url: /#contact
    weight: 40
