# Navigation Links

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 15
  - name: Papers
    url: /#papers
    weight: 20
  - name: Talks
    url: /#talks
    weight: 25
  - name: Projects
    url: /#projects
    weight: 30
  - name: Contact
    url: /#contact
    weight: 40
